addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.7")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.0")
addSbtPlugin("com.lightbend.sbt"  % "sbt-javaagent"   % "0.1.4")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.3.4")
